um/budget/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('api/add_transaction', AddTransactionView.as_view(), name='add_transaction_api'),
    path('api/remove_transaction', DeleteTransactionView.as_view(), name='remove_transaction_api'),
    path('api/status', JsonBudgetStatusView.as_view(), name='status_api'),
    path('manage', ManageBudgetsView.as_view(), name='manage'),
    path('api/budget_update', UpdateBudgetView.as_view(), name='budget_update_api'),
    path('api/budget_delete', DeleteBudgetView.as_view(), name='budget_delete_api'),
    path('manage_repeating_tx', ManageRepeatingTxView.as_view(), name='manage_repeating_tx'),
    path('api/repeating_tx_update', UpdateRepeatingTxView.as_view(), name='repeating_tx_update_api'),
    path('api/repeating_tx_end', EndRepeatingTxView.as_view(), name='repeating_tx_end_api'),
    path('api/tx_summary', TxAggregateSummary.as_view(), name='tx_summary_api'),
    path('manage_tx', ManageTxView.as_view(), name='manage_tx'),
    path('history', ListAllTxView.as_view(), name='history'),
    path('api/history', AllTxFragView.as_view(), name='history_api'),
    path('api/places', JsonSpecificPlacesView.as_view(), name='places_api'),
    path('demo', RedirectView.as_view(url='/accounts/demo?next=/budget', permanent=False), name='demo')
]

um/proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView

# only for dev
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('budget/', include('budget.urls')),
    path('accounts/', include('accounts.urls')),
    path('rando/', include('rando.urls')),
    path('', RedirectView.as_view(url='budget/', permanent=False))
] + static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)

um/budget/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models
from django.utils.timezone import now

import calendar
from datetime import date, timedelta
import math

from accounts.models import AccountsModel
from .enums import Durations


import logging
logger = logging.getLogger('proj')


class BaseModel(models.Model):
    class Meta:
        abstract = True

    created = models.DateField(auto_now_add=True)

    modified = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)


class TimespanMixin(models.Model):
    class Meta:
        abstract = True
    # in days, excluing 30 & 365 which are treated specially
    frequency = models.IntegerField(default=30, validators=[MinValueValidator(1)])

    start_date = models.DateField(default=now, editable=False, blank=False)

    end_date = models.DateField(default=date.max)



class SpecificPlacesModel(BaseModel):
    place = models.CharField(max_length=255, unique=True, validators=[MinLengthValidator(1)])

    def get_choice_pair(self):
        return (self.id, self.place)
    
    @classmethod
    def get_places_from_filter(cls, account_id: int, budget_id: int):
        what_budget = ' AND budget_id = ' + str(budget_id) if budget_id is not None  else ''
        raw_sql = '''
            SELECT uni.specific_place_id as id, place
            FROM (
                SELECT specific_place_id
                FROM budget_repeatingtransactionsmodel
                WHERE is_active AND account_id = %s''' + what_budget + '''
                UNION
                SELECT specific_place_id
                FROM budget_transactionsmodel
                WHERE is_active AND account_id = %s''' + what_budget + '''
            ) uni
            LEFT JOIN budget_specificplacesmodel
            ON uni.specific_place_id=budget_specificplacesmodel.id
        '''
        return SpecificPlacesModel.objects.raw(raw_sql, [account_id, account_id])

    def __str__(self):
        return self.place


class BudgetsModel(BaseModel, TimespanMixin):
    class Meta:
        unique_together = [['account', 'category']]

    account = models.ForeignKey(AccountsModel,
        on_delete=models.CASCADE
    )

    category = models.CharField(max_length=127, validators=[MinLengthValidator(1)])

    spending_limit = models.DecimalField(max_digits=15,
        decimal_places=2,
        default=0.00
    )

    def get_current_period(self):
        tday = date.today()
        return (tday-timedelta(days=self.frequency), tday)
    
    def get_choice_pair(self):
        return (self.id, self.category)

    def get_num_budget_cycles_in_range(self, range_start_date, range_end_date):
        actual_start_date = range_start_date if range_start_date > self.start_date else self.start_date
        actual_end_date = range_end_date if range_end_date < self.end_date else self.end_date

        num_cycles = 0
        match self.frequency:
            case Durations.YEARLY.value:
                num_cycles = actual_end_date.year - actual_start_date.year
            case Durations.MONTHLY.value:
                num_cycles = (actual_end_date.year - actual_start_date.year) * 12 + (actual_end_date.month - actual_start_date.month)
            case _: # daily, weekly, semi-monthly
                num_cycles = math.ceil((actual_end_date - actual_start_date).days / self.frequency)

        if num_cycles == 0 and range_start_date <= range_end_date:
            num_cycles = 1

        if num_cycles < 0:
            num_cycles = 0

        return num_cycles

    def spending_limit_over_range(self, range_start_date, range_end_date):
        return self.get_num_budget_cycles_in_range(range_start_date, range_end_date) * self.spending_limit


class BaseTransactionModel(BaseModel):
    class Meta:
        abstract = True

    account = models.ForeignKey(AccountsModel,
        on_delete=models.CASCADE
    )

    budget = models.ForeignKey(BudgetsModel,
        on_delete=models.CASCADE
    )

    specific_place = models.ForeignKey(SpecificPlacesModel,
        on_delete=models.CASCADE
    )

    amount = models.DecimalField(max_digits=15,
        decimal_places=2
    )


class TransactionsModel(BaseTransactionModel):
    class Meta:
        ordering = ['date']

    date = models.DateField(default=now, editable=False, blank=False)

    def __str__(self):
        return '({}, {}, {}, {}, {})'.format(
            self.account.username,
            self.kind,
            self.place,
            self.amount,
            self.date)


class RepeatingTransactionsModel(TimespanMixin, BaseTransactionModel):
    # this assumes that tx only begin on the days of the month in range [1, 28]
    # budget range can be on any day
    def get_first_tx_in_period(self, period_start_date):
        tx_begin_date = self.start_date
        if tx_begin_date >= period_start_date:
            return tx_begin_date
        else:
            month = period_start_date.month
            year = period_start_date.year
            day = tx_begin_date.day
            td = timedelta(days=0)
            match self.frequency:
                case Durations.MONTHLY.value:
                    if period_start_date.day > tx_begin_date.day:
                        month = (period_start_date.month % 12) + 1
                        year = period_start_date.year + math.floor(period_start_date.month / 12)
                case Durations.YEARLY.value:
                    year += 1
                case Durations.DAILY.value:
                    day = period_start_date.day
                case _: # everything else (weekly, semi-monthly) is literal days
                    num_tx = math.ceil((period_start_date - tx_begin_date).days / self.frequency)
                    td = timedelta(days = num_tx * self.frequency)
                    year = tx_begin_date.year
                    month = tx_begin_date.month
            return date(year=year, month=month, day=day) + td

    # this assumes that tx only begin on the days of the month in range [1, 28]
    # budget range can be on any day
    def get_num_tx_until_period_end(self, first_tx_in_period, period_end_date):
        num_tx = 1 # for the first tx
        match self.frequency:
            case Durations.MONTHLY.value:
                num_tx += (period_end_date.year - first_tx_in_period.year) * 12
                num_tx += period_end_date.month - first_tx_in_period.month
                # last one doesn't count if it hasn't happened yet
                if period_end_date.day < first_tx_in_period.day:
                    num_tx -= 1
            case Durations.YEARLY.value:
                num_tx += period_end_date.year - first_tx_in_period.year
                # if specific tx date for the final year in period, has not happened, don't count it
                if period_end_date < first_tx_in_period.replace(year=period_end_date.year):
                    num_tx -= 1
            case _: # everything else (daily, weekly, semi-monthly) is literal days
                num_tx += math.floor((period_end_date - first_tx_in_period).days / self.frequency)
        return num_tx
    
    def get_tx_dates_between_dates(self, first_date, second_date):
        dates = list()
        end_date_to_use = self.end_date if self.end_date < second_date else second_date
        start_date_to_use = first_date
        while True:
            first_tx = self.get_first_tx_in_period(start_date_to_use)
            if first_tx > end_date_to_use or first_tx == start_date_to_use:
                break
            else:
                dates.append(first_tx)
                start_date_to_use = first_tx + timedelta(days=1)
        return dates

    def get_num_tx_between_dates(self, first_date, second_date):
        end_date_to_use = self.end_date if self.end_date < second_date else second_date
        first_tx = self.get_first_tx_in_period(first_date)
        if first_tx > end_date_to_use:
            return 0
        else:
            return self.get_num_tx_until_period_end(first_tx, end_date_to_use)

    def get_num_tx_in_period(self):
        period = self.budget.get_current_period()
        return self.get_num_tx_between_dates(period[0], period[1])

    # assumes day of month to be in range [1, 28]
    # budget range can be on any day
    def amount_for_period(self):
        return self.amount * self.get_num_tx_in_period()

    def amount_between_dates(self, first_date, second_date):
        return self.amount * self.get_num_tx_between_dates(first_date, second_date)

um/budget/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from .enums import Durations
from .fields import DateDurationFormField, LowerCaseCharField, ActualDateField
from .fields import DefaultInvalidChoiceFormField
from .models import BudgetsModel, SpecificPlacesModel

import logging
logger = logging.getLogger('proj')


class BaseBudgetForm(forms.Form):
    class Meta:
        abstract = True

    required_css_class = 'required'


class IdentiferMixin(forms.Form):
    class Meta:
        abstract = True

    data_id = forms.IntegerField(initial=-1, widget=forms.HiddenInput())


class BudgetTxBaseForm(BaseBudgetForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.get_constraint_sql_from_request(request)
        budgets = BudgetsModel.objects.filter(account=request.user, is_active=True)
        cat = self.fields['category']
        cat.choices = cat.choices + [budget.get_choice_pair() for budget in budgets]
        cat.initial = self.category_filter
    
    category = DefaultInvalidChoiceFormField()

    def get_constraint_sql_from_request(self, request):
        try:
            # these are used in sql string concat, so check for sql injection if u change these lines
            self.category_filter = int(request.GET['category']) if 'category' in request.GET else None
        except:
            return True
        # these are always int or None, so no sql injection here
        self.what_budget = '' if self.category_filter == None else ' AND budget_id = ' + str(self.category_filter)
        return self.what_budget
    
    def get_form_url_params(self):
        result = list()
        if self.category_filter is not None:
            result.append('category=' + str(self.category_filter))
        return result


class BudgetChooserForm(BudgetTxBaseForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.get_constraint_sql_from_request(request)
        places = SpecificPlacesModel.get_places_from_filter(request.user.id, budget_id=self.category_filter)
        spp = self.fields['specific_place']
        spp.choices = spp.choices + [p.get_choice_pair() for p in places]
        spp.initial = self.sp_place_filter

    specific_place = DefaultInvalidChoiceFormField()

    def get_constraint_sql_from_request(self, request):
        try:
            # these are used in sql string concat, so check for sql injection if u change these lines
            self.sp_place_filter = int(request.GET['specific_place']) if 'specific_place' in request.GET else None
        except:
            return True
        # these are always int or None, so no sql injection here
        parent = super().get_constraint_sql_from_request(request)
        if parent == True:
            return True
        self.what_sp = '' if self.sp_place_filter == None else ' AND specific_place_id = ' + str(self.sp_place_filter)
        return self.what_sp + parent

    def get_form_url_params(self):
        result = super().get_form_url_params()
        if self.sp_place_filter is not None:
            result.append('specific_place=' + str(self.sp_place_filter))
        return result


class BaseTransactionForm(BudgetTxBaseForm, IdentiferMixin):
    class Meta:
        abstract = True

    amount = forms.FloatField(min_value=0.00, max_value=1e15)

    specific_place = LowerCaseCharField(max_length=255, min_length=1, required=False)


class DeleteDataForm(IdentiferMixin):
    pass


class AddTransactionForm(BaseTransactionForm):
    date = ActualDateField(required=False)

    is_repeating = forms.BooleanField(required=False)

    frequency = DateDurationFormField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['is_repeating']:
            if cleaned_data['frequency'] is None:
                self.add_error('frequency',
                    ValidationError('Frequency is required for repeating transactions.')
                )
            date = cleaned_data['date']
            if date is not None and date.day > 28:
                self.add_error('date',
                    ValidationError('Start Date cannot be on the 29th-31st of any month for '
                        + 'repeating transactions. Why? Because it made my maths easier.')
                )
        return cleaned_data


class UpdateRepeatingTxForm(BaseTransactionForm):
    frequency = DateDurationFormField()


class UpdateBudgetForm(IdentiferMixin, BaseBudgetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['placeholder'] = 'category'
        self.fields['spending_limit'].widget.attrs['placeholder'] = 'spending limit'

    spending_limit = forms.FloatField(min_value=0.00, max_value=1e15)

    category = LowerCaseCharField(max_length=127, min_length=1)

    frequency = DateDurationFormField()


# class WhenMoneyFreeForm(BaseTransactionForm):
#     pass

um/budget/templates/budget_base.html
{% extends "base_template.html" %}

{% block header %}
<link rel="stylesheet" href="/static/css/budget.css" type="text/css">
<script src="https://adoodleydo.dev/js/jquery.min.js"></script>
<script src="https://adoodleydo.dev/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/js/app.js"></script>
<script src="https://adoodleydo.dev/js/light.dark.js"></script>
<script type="text/javascript">
window.addEventListener("load", function () {
	$("nav").find("a").each(function (i, e) {
		if (e.href.endsWith(window.location)) {
			e.classList.add("disabled");
			e.parentElement.classList.add("active");
		}
	});
});
</script>
{% endblock %}

{% block title %}Budget Thingy{% endblock %}

{% block nav %}
<div class="navbar navbar-expand-md p-0 mb-1">

	<div class="mr-3 ml-3">
		<button class="navbar-toggler mr-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNav"
			aria-expanded="false" aria-controls="collapse" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<h5 class="mb-0 pt-1 pb-1 d-inline">Budget Thingy</h5>
	</div>

	<div class="collapse navbar-collapse" id="collapsibleNav">
		<div class="navbar-nav row m-0 p-0">
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pl-0 pr-0"
					href="{% url 'index' %}">Home</a>
			</label>
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pr-4 pl-4"
					href="{% url 'manage' %}">Budgets</a>
			</label>
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pr-4 pl-4"
					href="{% url 'manage_repeating_tx' %}">Repeating Transactions</a>
			</label>
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pr-4 pl-4"
					href="{% url 'history' %}">Transaction History</a>
			</label>
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pr-4 pl-4"
					href="{% url 'logout' %}">
				{% if request.user.id == 1 %}
					Leave Demo
				{% else %}
					Logout
				{% endif %}
				</a>
			</label>
			{% if request.user.id == 1 %}
			<label class="nav-item col-md p-0 m-0">
				<a class="nav-link light-dark-text text-center w-100 h-100 pr-4 pl-4"
					href="{% url 'signup' %}">
					Sign Up
				</a>
			</label>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

um/budget/templates/history.frag.html
{% load filters %}

<div class="history_item">
  <span id="id_is_repeating" class="hidden"></span>
  <div class="row p-1 ml-1 mr-1">
    <div class="col-6 col-sm-6 child-w-100 pl-0">
      <span id="id_specific_place"></span>
    </div>
    <div class="col-3 col-sm-3 child-w-100">
      <span id="id_amount"></span>
    </div>
    <div class="col-3 col-sm-3 child-w-100 pr-0">
      <span id="id_num_times"></span>
    </div>
    <span id="id_category" class="hidden"></span>
  </div>
  <hr class="mt-0 mb-0 mr-5 ml-5 p-0">
</div>

um/budget/templates/history.html
{% extends "budget_base.html" %}
{% load filters %}

{% block header %}
{{ block.super }}
<script src="/static/js/forms.js"></script>
<script src="/static/js/cache.js"></script>
<script src="/static/js/manage.generic.js"></script>
<script src="/static/js/manage.history.js"></script>
<script src="/static/js/history.js"></script>
<script src="/static/js/timespan.form.config.js"></script>
</script><!-- <script src="/static/js/add_transaction.js"></script> -->
{{ page.object_list|json_script:"pageData" }}
{% endblock %}

{% block content %}
<div class="text-bg container">
    <header class="pt-3">
      <form id="filterForm">
        <button type="button" class="btn btn-primary hidden"
          data-action="{% url 'history_api' %}" id="newBtn"
          onclick="window.listManage.new(event)">+ New Transaction</button>
        <div class="form group">
          <div class="form-row mb-1">
            <div class="col-sm-3 col-md-2">
              <label for="id_category">{{ form.category.label }}:</label>
            </div>
            <div class="col">
              {{ form.category|addcssclass:'form-control inline-form' }}
            </div>
          </div>
          <div class="form-row">
            <div class="col-sm-3 col-md-2">
              <label for="id_specific_place">{{ form.specific_place.label }}:</label>
            </div>
            <div class="col">
              {{ form.specific_place|addcssclass:'form-control inline-form' }}
            </div>
          </div>
          <div class="form-row">
            {% include "timespan.form.frag.html" %}
          </div>
        </div>
        <div class="d-flex justify-content-start">
          <button type="button" class="btn btn-primary" id="filterBtn" disabled="true">Apply filters</button>
        </div>
      </form>
      <hr>
    </header>
    <div id="formsContainer"></div>
    <div class="p-1" id="formInfo">
      <div class="p-5" id="noDataMsg">
        <p class="m-5 text-center">Your transactions will appear here.</p>
      </div>
    </div>
    {% include "pagination.frag.html" %}
  </div>
{% endblock %}

um/budget/templates/index.html
{% extends "budget_base.html" %}
{% load filters %}

{% block header %}
{{ block.super }}
<script src="https://adoodleydo.dev/js/popper.min.js"></script>
<script src="https://adoodleydo.dev/js/chart.min.js"></script>
<script src="https://adoodleydo.dev/js/palette.js"></script>
<script src="/static/js/history.graph.js"></script>
<script src="/static/js/forms.js"></script>
<script src="/static/js/add_transaction.js"></script>
<script src="/static/js/timespan.form.config.js"></script>
<script src="/static/js/index.js"></script>
{% endblock %}

{% block content %}
<div class="text-bg container">
	<div class="row">
		<div class="col-md col-md-6 col-lg-4 m-2 p-2 graph-sib">
			<!-- <form autocomplete="off"
					class="p-3 asky-form mb-4 border-bottom border-secondary">
				When will I have
				<input type="number" name="amount" placeholder="monies"
					class="form-control inline-form">
				in my
				{{ form.category|addcssclass:'form-control inline-form' }}
				budget?
				<i><b><span id="moneyAnswer"></span></b></i>
			</form> -->
			<button type="button" class="btn btn-primary"
				onclick="window.add_transaction.toggleTransactionForm(event)"
				data-bs-toggle="collapse" data-bs-target="#collapseAddTx"
				aria-expanded="false" aria-controls="collapseAddTx"
				id="addTxBtn">Add Transaction</button>
			<div class="collapse" id="collapseAddTx">
				<form method="post" autocomplete="off" onchange="$('#btn-submit')[0].disabled=false">
					{% csrf_token %}
					{{ form.data_id }}
					<fieldset>
						<div class="form-row form-group">
							<div class="invalid-feedback d-block __all___error">
								{{ form.non_field_errors | join:"<br>" }}
							</div>
						</div>
						<div class="form-row form-group">
							<div class="col-4 col-sm-4">
								{{ form.amount.label_tag }}
							</div>
							<div class="col-8 col-sm-8">
								{{ form.amount|addcssclass:'form-control' }}
								<div class="invalid-feedback d-block {{ form.amount.label|lower }}_error">
									{{ form.amount.errors | join:"<br>" }}
								</div>
							</div>
						</div>
						<div class="form-row form-group">
							<div class="col-4 col-sm-4">
								{{ form.category.label_tag }}
							</div>
							<div class="col-8 col-sm-8">
								{{ form.category|addcssclass:'form-control' }}
								<div class="invalid-feedback d-block {{ form.category.label|lower }}_error">
									{{ form.category.errors | join:"<br>" }}
								</div>
							</div>
						</div>
						<div class="form-row form-group">
							<div class="col-4 col-sm-4">
								{{ form.specific_place.label_tag }}
							</div>
							<div class="col-8 col-sm-8">
								{{ form.specific_place|addcssclass:'form-control' }}
								<div class="invalid-feedback d-block {{ form.specific_place.label|lower }}_error">
									{{ form.specific_place.errors | join:"<br>" }}
								</div>
							</div>
						</div>
						<div class="form-row form-group">
							<div class="col-4 col-sm-4" id="dateLabelContainer">
								{{ form.date.label_tag }}
							</div>
							<div class="col-8 col-sm-8">
								{{ form.date|addcssclass:'form-control' }}
								<div class="invalid-feedback d-block {{ form.date.label|lower }}_error">
									{{ form.date.errors | join:"<br>" }}
								</div>
							</div>
						</div>
						<div class="form-row form-group">
							<div class="col-4 col-sm-4">
								<label for="id_is_repeating">Repeating Transaction:</label>
							</div>
							<div class="col-8 col-sm-8">
								<div class="custom-control custom-switch">
									<input type="checkbox" autocomplete="off" id="id_is_repeating" name="is_repeating"
										class="custom-control-input"
										data-bs-toggle="collapse" data-bs-target="#collapseRepeating"
										aria-expanded="false" aria-controls="collapseRepeating"
										onchange="window.add_transaction.toggleRepeatingTransaction(event)">
									<label for="id_is_repeating" class="custom-control-label"></label>
								</div>
							</div>
						</div>
						<div class="collapse" id="collapseRepeating">
							<div class="form-row form-group">
								<div class="col-4 col-sm-4">
									<label for="id_frequency" class="required">{{ form.frequency.label }}:</label>
								</div>
								<div class="col-8 col-sm-8">
									{{ form.frequency|addcssclass:'form-control' }}
									<div class="invalid-feedback d-block {{ form.frequency.label|lower }}_error">
										{{ form.frequency.errors | join:"<br>" }}
									</div>
								</div>
							</div>
						</div>
					</fieldset>

					<div class="form-row">
						<div class="col-sm-8"></div>
						<input type="button" id="btn-submit" class="btn btn-primary align-self-end col-sm-3"
							data-action="{% url 'add_transaction_api' %}" value="Submit"
							onclick="window.add_transaction.submitTransaction(event)">
					</div>
				</form>
			</div>
			<hr>
			{% include "timespan.form.frag.html" %}
		</div>
		<div class="col col-lg col-lg-8 position-relative" id="mainGraphContainer">
			<canvas id="mainGraph" width="300" height="300"></canvas>
		</div>
		<div class="col-lg col-lg-8 p-5 d-none m-3" id="noDataMsg">
			<p class="m-5 text-center">
				Your budget usage will appear here.
				<a href="{% url 'manage' %}">Add a budget</a>.
			</p>
		</div>
	</div>
</div>
{% endblock %}

um/budget/templates/manage_budgets.html
{% extends "budget_base.html" %}
{% load filters %}

{% block header %}
{{ block.super }}
<script src="/static/js/forms.js"></script>
<script src="/static/js/cache.js"></script>
<script src="/static/js/manage.generic.js"></script>
<script src="/static/js/manage.budgets.js"></script>
{{ page.object_list|json_script:"pageData" }}
{% endblock %}

{% block content %}
<div class="text-bg container">
  <header class="pt-3">
    <h3>
      <button type="button" class="btn btn-primary"
        data-action="{% url 'budget_update_api' %}" id="newBtn"
        onclick="window.listManage.new(event)">+ New Budget</button>
    </h3>
    <hr>
  </header>
  <div id="formsContainer"></div>
  <div class="p-1" id="formInfo">
    {% csrf_token %}
    <div class="p-5" id="noDataMsg">
      <p class="m-5 text-center">Your budgets will appear here.</p>
    </div>
  </div>
  {% include "pagination.frag.html" %}
</div>
{% endblock %}

um/budget/templates/update_tx.frag.html
{% load filters %}

<form class="row p-1" autocomplete="off" method="post"
    onchange="$(this).find('.save-btn')[0].disabled=false">
  {{ form.data_id }}
  {{ form.is_repeating|addcssclass:'hidden' }}
  {{ form.frequency|addcssclass:'hidden' }}
  <fieldset class="pr-2 pl-2 pb-1 pt-0">
    <small id="id_date"></small>
    <div class="form-row form-group m-1"
        onfocusin="window.forms.accordion($(this).siblings('.accordion-member'))">
      <div class="col-4 col-sm-4 child-w-100 pl-0">
        {{ form.category|addcssclass:'form-control' }}
      </div>
      <div class="col-4 col-sm-4 child-w-100">
        {{ form.specific_place|addcssclass:'form-control' }}
      </div>
      <div class="col-4 col-sm-4 child-w-100 pr-0">
        {{ form.amount|addcssclass:'form-control' }}
      </div>
    </div>
    <div class="form-row">
      <div class="col-4 col-sm-4 invalid-feedback d-block m-0 category_error">
        {{ form.category.errors | join:"<br>" }}
      </div>
      <div class="col-4 col-sm-4 invalid-feedback d-block m-0 specific_place_error">
        {{ form.specific_place.errors | join:"<br>" }}
      </div>
      <div class="col-4 col-sm-4 invalid-feedback d-block m-0 amount_error">
        {{ form.amount.errors | join:"<br>" }}
      </div>
    </div>
    <div class="form-row">
      <div class="invalid-feedback d-block m-0 __all___error">
        {{ form.non_field_errors | join:"<br>" }}
      </div>
    </div>
    <div class="form-group m-1 mt-2 collapse accordion-member">
      <div class="d-flex justify-content-between">
        <button type="button" class="btn btn-danger"
          data-action="{% url 'remove_transaction_api' %}"
          onclick="window.listManage.delete(event)">Delete</button>
        <div id="saveFeedback" class="pt-2 pr-2 w-100 text-right text-success" style="display:none">Saved!</div>
        <button type="button" class="btn btn-success save-btn"
          data-action="{% url 'add_transaction_api' %}"
          onclick="window.listManage.save(event)" disabled="true">Save</button>
      </div>
    </div>
  </fieldset>
</form>